Enforce Sendable conformance for LogHandlers Swift-Log, and make Logger Sendable
apple/swift-log pull request #217
Opened 2022-02-04 14:22 UTC by Joannis

Enforce Sendable conformance for LogHandlers Swift-Log, and make Logger Sendable. See #216 

### Motivation:

Swift-Log is adopted in many libraries, and as the language has recently involved in exciting new directions, these new features have been the subject of improvement and innovation. Many libraries aim at implementing `Sendable`, which means that many types that carry swift-log's `Logger` will quickly see warnings pop up all over these projects.

As swift-log is a loved and essential part of the swift ecosystem, it too should adopt the new Swift standards.

### Modifications:

- Require `LogHandler` implementations to conform to `Sendable`
- Conform `Logger` to `Sendable`
- Updated tests to support the new Sendable requirements

### Result:

Swift-Log supports Sendable. Requires iOS 13+, macOS 10.15+ and Swift 5.5+.
This'll obviously require a semver major.

2022-02-04 14:25 UTC, Joannis commented
That bot is very eager for a review!

2022-02-09 03:12 UTC, ktoso commented
@swift-server-bot test this please

2022-02-09 03:13 UTC, ktoso commented on Package.swift
> +    ],
can't just do that like this; we need to support old platforms too

2022-02-09 03:14 UTC, ktoso commented on Sources/Logging/LogHandler.swift
> +public protocol LogHandler: Sendable {
can't just do it like this, we'd need to follow the trickery with the sendable availability as explained in https://github.com/swift-server/guides/blob/main/docs/concurrency-adoption-guidelines.md#backwards-compatibility-of-declarations-and-checked-swift-concurrency

So we'd need `_SwiftLog_Sendable` and the entire dance

2022-02-09 04:50 UTC, ktoso commented on Sources/Logging/Logging.swift
> +    public typealias Stream = TextOutputStream & Sendable
has to use the compatibility trickery

2022-02-09 04:50 UTC, ktoso requested changes
Not quite right, we need to treat this very carefully so older clients can still adopt even if they are on old swift IMHO

2022-07-26 07:04 UTC, ktoso commented
Sendable conformance has been done in https://github.com/apple/swift-log/pull/218 in a more compatible way.

Thank you for the PR though!

2022-07-26 07:04 UTC, closed without merging

2024-03-12 10:34 UTC, easydev991 commented
> Sendable conformance has been done in #218 in a more compatible way.
> 
> Thank you for the PR though!

Hello! I still get warning about Logger not being `Sendable` inside a `Sendable`-class. Is it a new feature in Xcode 15.3, or is it a bug?

2024-03-12 10:37 UTC, Lukasa commented
Can you show your code? Are you storing it as `var`?

2024-03-12 14:24 UTC, easydev991 commented
> Can you show your code? Are you storing it as `var`?

Cannot show the code now.
I store it as a `let` inside a `@MainActor`-class

2024-03-12 14:30 UTC, Lukasa commented
What version of swift-log have you resolved?

2024-03-12 14:39 UTC, easydev991 commented
> What version of swift-log have you resolved?

I do not use swift-log, I `import OSLog` and then use `Logger` inside a class like this:
```swift
import OSLog

@MainActor
protocol SomeProtocol {}

final class MyClass: SomeProtocol {
  private let logger = Logger(subsystem: "Subsystem", category: "MyClass")
}
```

An interesting moment: in one file it helped me to make `@preconcurrency import OSLog`, but in other file it does not work. I have strict concurrency check (complete) in my app build settings.

2024-03-12 14:55 UTC, Lukasa commented
This repository is not for os log, it's for swift-log. Issues with os log should be taken to [Apple's developer forums](https://developer.apple.com/forums/).