Default subscript implementation.
apple/swift-log pull request #246
Opened 2023-01-08 07:13 UTC by nashysolutions

The `LogHandler` protocol provides a default implementation of the metadata subscript function.

### Motivation:

The requirement for a subscript seems unnecessary, given that it's typically boilerplate.

### Modifications:

- Deleted the requirement from the protocol signature. 
- Installed a default implementation in the protocol extension.

### Result:

The library user no longer has to provide the boilerplate.

2023-01-09 02:24 UTC, ktoso commented
Thanks for the PR but that'd change behavior in existing adopting libraries and potentially cause breaking issues, if they really did something else in those implementations -- I don't think this is a safe change to apply.

2023-01-09 02:25 UTC, ktoso requested changes
I don't think this is a safe change to apply, the win from trying to make it happen also seems rather small so I don't think we need to pursue this further 🤔

2023-01-09 06:36 UTC, nashysolutions commented
I don't see why it would be unsafe. Happy to close, if you think that's best.

2023-01-09 08:09 UTC, nashysolutions commented
> Thanks for the PR but that'd change behavior in existing adopting libraries and potentially cause breaking issues, if they really did something else in those implementations -- I don't think this is a safe change to apply.

Here is an example implementation of how this change does not cause a break. The print statement 'setting' still prints in each scenario.

```swift
protocol Vehicle {
    var store: [String: String] { get set }
    
    // Remove this to test
    subscript(attribute key: String) -> String?
}

// Remove this to test
extension Vehicle {
    
    subscript(attribute key: String) -> String? {
        get {
            store[key]
        }
        set {
            store[key] = newValue
        }
    }
}

struct Car: Vehicle {
    
    var store: [String: String] = [:]
    
    subscript(attribute key: String) -> String? {
        get {
            store[key]
        }
        set {
            print("setting")
            store[key] = newValue
        }
    }
}

struct ContentView: View {
    
    init() {
        var car = Car()
        car[attribute: "fuel"] = "petrol"
        print(car.store)
    }
        
    var body: some View {
        Text("Hello, World!")
    }
}
```

2023-01-12 02:50 UTC, ktoso commented
Sure. 

- Removing the protocol requirement gets us to a non-working customization point, libs would compile, but not work as expected -- that's the state of this PR. The bad behavior is shown by my snippets above. 

You also mention to remove the extension, but if we do that, we have non-compiling code:

- Removing the protocol requirement AND the extension results in non-compiling swift-log, since we must be calling this subscript, but there is no declaration of it anywhere, i.e.:

```
error: repl.swift:75:8: error: value of type 'any Vehicle' has no subscripts
    car[attribute: "fuel"] = "petrol"
```

So... no, wa can't make this change, in any way you intended those "remove to test" to be interpreted, they result either in incorrect or non compiling code.

If you mean removing "just the extension" is just status quo of the library as it is today.

I'm going to close this PR if you don't mind, there's nothing actionable we can do here AFAICS.

2023-01-12 02:50 UTC, closed without merging

2023-01-12 03:28 UTC, nashysolutions commented
The part I missed in your example, was the casting to vehicle.

```swift
var car: Vehicle = Car()
```

I didn't quite realise this behaviour when removing the requirement but keeping an extension. Apologies.