Explicitly set the type of the SPM library to be dynamic.
apple/swift-log pull request #289
Opened 2024-02-14 10:55 UTC by jon-mccormack

Explicitly set the type of the SPM library to be dynamic.

Motivation:

When a binary target-type framework consumer specifies swift-log as a transitive dependency, the swift-log symbols that the framework depends on are statically linked in that framework's binary. As a result, consumers of said framework resolve the swift-log transitive dependency which is made available as a dynamic library at runtime - meaning duplicate symbols are present in two (or more) different dynamic libraries causing "Class is implemented in both..." warning logs.

Downstream app warning logs at runtime:
![image](https://github.com/apple/swift-log/assets/55437880/adac708e-0bb9-4855-8adb-b70c2fa5180b)

Proof of swift-log symbols being statically linked in my binary framework consumer:
![image](https://github.com/apple/swift-log/assets/55437880/8477ea7a-fefd-49f8-bb7f-5571d4dee65a)

Modifications:

To resolve this, I have explicitly set the SPM library type of swift-log to 'dynamic'. This means binary target-type consumers link swift-log dynamically.

Result:

Binary target-type framework consumers of swift-log will get the same experience as regular source-code consumers of swift-log as swift-log will be linked dynamically rather than statically.

I've tried and tested this fork in an app which resolves my binary target-type framework through SPM and swift-log (as a transitive dependency) and I no longer get those warnings.

Proof of swift-log symbols no longer being statically linked to binary target-type consumers after my change:
![image](https://github.com/apple/swift-log/assets/55437880/7aafc1a8-94e9-4131-ae5d-aeee67c358e4)

2024-02-14 21:17 UTC, Lukasa requested changes
Thanks for this patch! However, I am worried that we can’t accept it in its current form. This may well break distribution for many existing Linux or command-line SwiftPM users, who do not expect an extra dylib to be needed for app distribution. 

@yim-lee, can you comment on whether there is a better way to resolve this issue?

2024-02-14 21:35 UTC, yim-lee commented
@MaxDesiatov @neonichu Do you have any recommendation here?

2024-02-14 22:02 UTC, neonichu commented
Not sure how the originator is planning to distribute swift-log with their XCFramework, typically the way to resolve this is to rename symbols. Relying on clients to bring their own copy of swift-log is not something that'll work in the general case.

2024-02-15 12:29 UTC, MaxDesiatov commented
I don't think this should be merged. The status quo with the default `.auto` setting in this package is the right approach as it provides the flexibility to link it either statically or dynamically. Restricting this package only to dynamic linking will break a lot of things for packages depending on `swift-log` and degrade performance when compared to the static linking option.

2024-02-15 14:28 UTC, MaxDesiatov commented
> The only solution I think for people in a similar scenario as me is to just deal with the class implemented in both warning at runtime.

There's no way to deal with duplicate symbols other than avoiding them in the first place. IMO in most cases those should be errors and not warnings. Loading multiple symbols with the same name is undefined behavior causing hard to diagnose possibly non-deterministic bugs.

2024-02-15 15:10 UTC, jon-mccormack commented
> There's no way to deal with duplicate symbols other than avoiding them in the first place. IMO in most cases those should be errors and not warnings. Loading multiple symbols with the same name is undefined behavior causing hard to diagnose and possibly non-deterministic bugs.

Yeah, I agree with this completely. I still think, though, that this boils down to a lack of support for binary dependencies in SwiftPM/XCode. Perhaps I'll have to work around having any dependencies for my binary framework altogether, given the unsafe, non-deterministic nature of loading one of many class definitions at runtime.

Thanks everyone for your input on this! I'm happy for my PR to be rejected, given our collective findings.

2024-02-15 15:16 UTC, MaxDesiatov commented
> this boils down to a lack of support for binary dependencies in SwiftPM/XCode

No debating that, but then it's worth finding an existing issues or filing a new one on the SwiftPM repo for CLI `swift build` use cases, and then a separate one on https://feedbackassistant.apple.com for Xcode, since implementations for these two are separate.

2024-02-15 17:03 UTC, closed without merging

2024-02-15 17:03 UTC, yim-lee commented
Thanks folks for the discussion. Closing this PR.