Update README.md add shipbook as backend
apple/swift-log pull request #304
Opened 2024-05-19 09:05 UTC by elishas

added shipbook as backend for the libratry

### Motivation:

added shipbook as backend for the libratry

### Modifications:

Just added it to the backend list 

### Result:

will have a fuller list

2024-05-20 11:53 UTC, gjcairo requested changes
Can we keep this list as append-only and put this entry at the end instead of prepending it?

2024-05-20 11:53 UTC, gjcairo commented on README.md
> +| [ShipBook/swift-log-**shipbook**](https://github.com/ShipBook/swift-log-shipbook) | a logging backend that sends log entries to [Shipbook](https://www.shipbook.io) - Shipook gives you the power to
Typo:
```suggestion
| [ShipBook/swift-log-**shipbook**](https://github.com/ShipBook/swift-log-shipbook) | a logging backend that sends log entries to [Shipbook](https://www.shipbook.io) - Shipbook gives you the power to remotely gather, search and analyze your user logs and exceptions in the cloud, on a per-user & session basis. |
```

2024-05-22 06:54 UTC, elishas commented
Sure

2024-06-19 09:07 UTC, PeterAdams-A commented
> Sure

@elishas I think Gus was expecting you to do a follow up commit to move it to the end of the list.

2024-06-20 12:14 UTC, gjcairo approved these changes

2024-06-20 12:14 UTC, PeterAdams-A commented
@swift-server-bot test this please

2024-06-20 12:18 UTC, merged